package com.shopping.service.util;



import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import com.shopping.service.model.EmailParams;

public class SendEmail {

	public static void main(String[] args) {
//		sendEmail("priyanka.g030890@gmail.com","Registration successful", "Hello, you have been registered.");
		

}
	private static String host = "smtp.gmail.com";
	private static String emailFrom = "priyadikondawar@gmail.com";
	
	public static Properties getProperties() {
		Properties properties = System.getProperties();
		properties.put("mail.smtp.host", host);
		properties.put("mail.smtp.port", 465);
		properties.put("mail.smtp.ssl.enable", true);
		properties.put("mail.smtp.auth", true);
		return properties;
		
	}

		public static void sendEmail(EmailParams emailParams) {
		
		Properties properties = getProperties();
		
		Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
		          return new PasswordAuthentication(emailFrom, "kych ktcm ibin csoh"); //WP Mail SMTP - the password used is app password generated by google after 2 step varification
			
		}		

	});
		
		MimeMessage message = new MimeMessage(session);
		try {
			message.setFrom(new InternetAddress(emailFrom));
			message.addRecipient(Message.RecipientType.TO, new InternetAddress(emailParams.getEmailTo()));
			message.setSubject(emailParams.getSubject());
			message.setText(emailParams.getEmailBody());
			Transport.send(message);
		} catch (AddressException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
